### PR TITLE
Update OpenCV Templates to the new Shared Memory Implementation

### LINKED ISSUE #161: New template blocks OpenCV collection
Visualcircuit is moving to Python 3.8's shared memory implementation, with a new template for blocks, that hides implementation details of wires. This issue is for migrating old template OpenCV blocks to the new format.

Drivers:

- [x] Camera
- [x] Image Read
- [x] Video  Streamer
- [x] Screen

Processing:

- [x] Blur
- [x] ColorFilter
- [x] ContourDetector
- [x] Cropper
- [x] Dilation
- [x] Edge Detector
- [x] Erosion
- [x] Face Detector
- [x] Threshold

### PR DESCRIPTION
**Pull request by toshan-luktuke**
Updated the templates for all the OpenCV blocks. 

New templates have been tested on Linux

Fix #161

### CODE REVIEW

**Comment by toshan-luktuke** [comment]
Should I minify these json files before merging?

**Comment by Suhas-G** [comment]
Hello...Sorry I was able to review the code just today...I see a frequency parameter in most blocks. So we don't need a separate frequency parameter anymore. It's part of the code block itself.

**Comment by Suhas-G** [comment]
1. Face Detector - I think we can refactor the code a bit
```python
    if choice == 'image':
        while(auto_enable or inputs.read_number('Enable')):
            img = inputs.read_image("Img")
            if img is None:
                continue
            bboxes = classifier.detectMultiScale(img)

            for box in bboxes:
                x, y, x1, y1 = box
                x1, y1 = x+x1, y+y1
                cv2.rectangle(img, (x, y), (x1, y1), (0,255,0), 2)
            outputs.share_image('Out', img)
            synchronise()
                
    else:
        while(auto_enable or inputs.read_number('Enable')):        
            img = inputs.read_image("Img")
            if img is None:
                continue
            bboxes = classifier.detectMultiScale(img)
            
            to_write = [320, 240, 0, 0]
            for box in bboxes:
                to_write = [box[0], box[1], box[2], box[3]]
                break
            outputs.share_array("Out", to_write)
            synchronise()
```
can be 
```python
while(auto_enable or inputs.read_number('Enable')):
    img = inputs.read_image("Img")
    if img is None:
        continue
    bboxes = classifier.detectMultiScale(img)
    
    if choice == 'image':
          for box in bboxes:
              x, y, x1, y1 = box
              x1, y1 = x+x1, y+y1
              cv2.rectangle(img, (x, y), (x1, y1), (0,255,0), 2)
          outputs.share_image('Out', img)
    else:
          to_write = [320, 240, 0, 0]
          for box in bboxes:
               to_write = [box[0], box[1], box[2], box[3]]
               break
           outputs.share_array("Out", to_write)
    
    synchronise()
```

2.  Blur - The order seems to be other way round.

```python
if .....
     .......
elif blur_type == 'Averaging':
      blurred_img = cv2.medianBlur(frame, kernel[0])
                        
elif blur_type == 'Median':
      blurred_img = cv2.blur(frame, kernel)
```

3. Screen - Default value of auto_enable (This was probably my mistake when I sent the file :))
```python
auto_enable = False #missing
try:
     enable = inputs.read_number('Enable')
except Exception:
     auto_enable = True
```



And regarding minifiying JSON files.... I don't know why it's not automatically minified....
Didn't you download the VC file from web editor?

**Comment by toshan-luktuke** [comment]
I accidentally formatted some files myself and committed them... apologies I'll minify all of them now.
I'll remove the Frequency constant as well, and submit with the other changes in a bit

**Comment by toshan-luktuke** [comment]
Changes made:

- [x] Frequency block has been removed
- [x] All files are minified
- [x]  Add declaration for auto_enable in Screen
- [x] Order changed in Blur
- [x] Refactored code for Face Detector
- [x] Changed version name from `v2.0` -->  `2.0.0` in Screen, ColourFilter and Camera (changed to be consistent with all other blocks)

**Pull request merged**
